export const GET_USER_DETAILS_REQUEST = 'almond/GET_USER_DETAILS_REQUEST';
export type GET_USER_DETAILS_REQUEST = typeof GET_USER_DETAILS_REQUEST;

export const GET_USER_DETAILS_SUCCESS = 'almond/GET_USER_DETAILS_SUCCESS';
export type GET_USER_DETAILS_SUCCESS = typeof GET_USER_DETAILS_SUCCESS;

export const GET_USER_DETAILS_FAILURE = 'almond/GET_USER_DETAILS_FAILURE';
export type GET_USER_DETAILS_FAILURE = typeof GET_USER_DETAILS_FAILURE;

export const GET_ALL_USERS_REQUEST = 'almond/GET_ALL_USERS_REQUEST';
export type GET_ALL_USERS_REQUEST = typeof GET_ALL_USERS_REQUEST;

export const GET_ALL_USERS_SUCCESS = 'almond/GET_ALL_USERS_SUCCESS';
export type GET_ALL_USERS_SUCCESS = typeof GET_ALL_USERS_SUCCESS;

export const GET_ALL_USERS_FAILURE = 'almond/GET_ALL_USERS_FAILURE';
export type GET_ALL_USERS_FAILURE = typeof GET_ALL_USERS_FAILURE;

export const EDIT_USER_DETAILS_SUCCESS = 'almond/EDIT_USER_DETAILS_SUCCESS';
export type EDIT_USER_DETAILS_SUCCESS = typeof EDIT_USER_DETAILS_SUCCESS;

export const EDIT_USER_DETAILS_FAILURE = 'almond/EDIT_USER_DETAILS_FAILURE';
export type EDIT_USER_DETAILS_FAILURE = typeof EDIT_USER_DETAILS_FAILURE;

export const EDIT_USER_ROLE_SUCCESS = 'almond/EDIT_USER_ROLE_SUCCESS';
export type EDIT_USER_ROLE_SUCCESS = typeof EDIT_USER_ROLE_SUCCESS;

export const EDIT_USER_ROLE_FAILURE = 'almond/EDIT_USER_ROLE_FAILURE';
export type EDIT_USER_ROLE_FAILURE = typeof EDIT_USER_ROLE_FAILURE;

export const LOG_OUT_USER = 'almond/LOG_OUT_USER';
export type LOG_OUT_USER = typeof LOG_OUT_USER;
