export const ADD_DEVICE_REQUEST = 'almond/device/ADD_DEVICE_REQUEST';
export type ADD_DEVICE_REQUEST = typeof ADD_DEVICE_REQUEST;

export const ADD_DEVICE_SUCCESS = 'almond/devices/ADD_DEVICE_SUCCESS';
export type ADD_DEVICE_SUCCESS = typeof ADD_DEVICE_SUCCESS;

export const ADD_DEVICE_FAILURE = 'almond/device/ADD_DEVICE_FAILURE';
export type ADD_DEVICE_FAILURE = typeof ADD_DEVICE_FAILURE;

export const USER_VERIFY_DEVICE_REQUEST = 'almond/device/USER_VERIFY_DEVICE_REQUEST';
export type USER_VERIFY_DEVICE_REQUEST = typeof USER_VERIFY_DEVICE_REQUEST;

export const USER_VERIFY_DEVICE_SUCCESS = 'almond/devices/USER_VERIFY_DEVICE_SUCCESS';
export type USER_VERIFY_DEVICE_SUCCESS = typeof USER_VERIFY_DEVICE_SUCCESS;

export const USER_VERIFY_DEVICE_FAILURE = 'almond/device/USER_VERIFY_DEVICE_FAILURE';
export type USER_VERIFY_DEVICE_FAILURE = typeof USER_VERIFY_DEVICE_FAILURE;

export const ACTIVATE_DEVICE_REQUEST = 'almond/device/ACTIVATE_DEVICE_REQUEST';
export type ACTIVATE_DEVICE_REQUEST = typeof ACTIVATE_DEVICE_REQUEST;

export const ACTIVATE_DEVICE_SUCCESS = 'almond/devices/ACTIVATE_DEVICE_SUCCESS';
export type ACTIVATE_DEVICE_SUCCESS = typeof ACTIVATE_DEVICE_SUCCESS;

export const ACTIVATE_DEVICE_FAILURE = 'almond/device/ACTIVATE_DEVICE_FAILURE';
export type ACTIVATE_DEVICE_FAILURE = typeof ACTIVATE_DEVICE_FAILURE;
