export const GET_ENVIRONMENT_DATA_REQUEST = 'almond/sensor/GET_ENVIRONMENT_DATA_REQUEST';
export type GET_ENVIRONMENT_DATA_REQUEST = typeof GET_ENVIRONMENT_DATA_REQUEST;

export const GET_ENVIRONMENT_DATA_SUCCESS = 'almond/sensor/GET_ENVIRONMENT_DATA_SUCCESS';
export type GET_ENVIRONMENT_DATA_SUCCESS = typeof GET_ENVIRONMENT_DATA_SUCCESS;

export const GET_ENVIRONMENT_DATA_FAILURE = 'almond/sensor/GET_ENVIRONMENT_DATA_FAILURE';
export type GET_ENVIRONMENT_DATA_FAILURE = typeof GET_ENVIRONMENT_DATA_FAILURE;

export const GET_WATER_DATA_REQUEST = 'almond/sensor/GET_WATER_DATA_REQUEST';
export type GET_WATER_DATA_REQUEST = typeof GET_WATER_DATA_REQUEST;

export const GET_WATER_DATA_SUCCESS = 'almond/sensor/GET_WATER_DATA_SUCCESS';
export type GET_WATER_DATA_SUCCESS = typeof GET_WATER_DATA_SUCCESS;

export const GET_WATER_DATA_FAILURE = 'almond/sensor/GET_WATER_DATA_FAILURE';
export type GET_WATER_DATA_FAILURE = typeof GET_WATER_DATA_FAILURE;
